### DISCUSSION TITLE
Is it possible to change default dashboard port (3333) to standard https (443)?

### DISCUSSION THREAD

**Discussion by denistorresan** [swiftwave-org/swiftwave#779] [Q&A] [answered]
Hi,
I just installed swiftwave, and figure out that dashboard URL (with https enabled) is something like:

https://console.example.com:3333

is it possible to configure Swiftwave to use 443 port instead?

https://console.example.com

thank you!

**Comment by tanmoysrt** [comment]
Actually the proxy server run on port 80, 443 by default, So we choose to use any other port except that for swiftwave. Because, if proxy or anything starts malfunctioning due to any reason, you need access to dashboard to fix the issue.

If you are fine to run swiftwave on any port other than 3333, just run swiftwave config -e vim  . You will find a section at top, you can configure that like this.
```yaml
service:
    use_tls: false
    management_node_address: <domain_name>
    auto_renew_management_node_cert: false
    bind_address: 0.0.0.0
    bind_port: <custom_port>
    ssh_timeout: 10
```

- Exposing a non-standard port doesn't cause any issue because no other process is going to bind to that port. And on port 3333 or anything other than that, you can also secure it with https, swiftwave tls generate command.

- If you still want to make swiftwave dashboard accessible at port 443, you need to utilize the proxy for this. If you need this let me know. Because it's not documented. I can send you the steps after a bit.

**Reply by denistorresan** [reply, marked as answer]
Your solution works!

1. First disable tls of swiftwave by `swiftwave tls disable`
2. Now visit the dashboard using `http`  url of dashboard first
3. Go to `Manage Routing > Domains` and register a domain and wait few seconds to auto issue the SSL
4. Go to `Manage Routing > Ingress Rules` , Create a ingress rule. Choose the domain with HTTPS, and under application dropdown section, you will see a text button `Need to expose some external services ? Click Here` , click on that.
5. SSH to server and get the server's private IP using `ifconfig`, look for `docker0` IP
6. In external service, put the server's private IP address and port 3333.
7. Now you may access the dashboard at that specific domain. Block this 3333 port from external firewall as well via UWP.


Additionally do this config to run `swiftwave` with this kind of configuration. As you are running `swiftwave` without TLS, it require some more configuration to run normally.

**Running single server ?**
- Open configuration `swiftwave config -e vim`
- Edit the config and put `management_node_address` and put the domain name there.

  ```
   management_node_tunnelling:
      enabled: true
      management_node_address: dashboard.example.com
      management_node_port: 443
      local_image_registry_node_address: 127.0.0.1
      local_image_registry_node_port: 3334
  ```
 - Restart using `swiftwave service restart`

**Running on cluster ?**
- Open configuration `swiftwave config -e vim`
- Edit the config and put `management_node_address` and put the domain name there. And in `local_image_registry_node_address` put the private ip of your server.
  ```
   management_node_tunnelling:
      enabled: true
      management_node_address: dashboard.example.com
      management_node_port: 443
      local_image_registry_node_address: 10.0.2.1
      local_image_registry_node_port: 3334
  ```
- Restart using `swiftwave service restart`
- Now, on each server you need to mark `10.0.2.1:3334` registry as secured one.
- Create or edit `/etc/docker/daemon.json` the file
  
   ```
   {
       "insecure-registries" : [ "10.0.2.1:3334" ]
   }
   ```
- Run `sudo service docker restart` on the server
- You need to do this for each server on the cluster
