### ISSUE TITLE
bug: Can't proceed installing stack file cointaining no variables

### ISSUE THREAD

**Issue by zaniar** [swiftwave-org/swiftwave#1003]
### Describe the bug

Here is the stack file

```yaml
services:
  "{{STACK_NAME}}":
    image: benbusby/whoogle-search:latest
    expose:
      - "5000/http/Whoogle Endpoint"
docs:
  logo_url: "https://getumbrel.github.io/umbrel-apps-gallery/whoogle-search/icon.svg"
  name: "Whoogle"
  description: "Whoogle is a self-hosted, privacy-focused search engine front-end for accessing Google search results without tracking and data collection."
  readme_description: >
    Get Google search results, but without any ads, JavaScript, AMP links, cookies, or IP address tracking. Easily deployable in one click as a Docker app, and customizable with a single config file. Quick and simple to implement as a primary search engine replacement on both desktop and mobile.
    
    ### Links

    - Official Wesbite - [github.com/benbusby/whoogle-search](https://github.com/benbusby/whoogle-search)

  iframe_video_embed: ""
```

**Start Installation** button is disabled

![image](https://github.com/user-attachments/assets/f02cfe16-d45a-46c0-9aa3-d40fcf52e024)

### Are you working on this issue?

No

**Comment by tanmoysrt** [comment]
Hi @zaniar 

Add a blank list to variables
```
  variables: []
```
That should fix the issue.

**Comment by tanmoysrt** [comment]
Hi @zaniar 

Got it. It's happening as `variables` key marked as null by yaml specs. I haven't thought about this case, as most apps requires atleast one variable.

To bypass this, just add a dummy variable and you can put a message for user like below.

```
  variables:
    JUST_A_MESSAGE:
      title: "🙂 That's all!"
      description: "You don't need to configure anything else here"
      default: ""
      type: "markdown"
      options:
```
(you can put empty string in title and description, if you don't want to show anything)

If more case arises like this, we can fix the behaviour.
