### ISSUE TITLE
feat: (minimal) `docker stack` support

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#203]
Swiftwave will provide support for a subset of Stack features. (It will power one click app store [in future])

```yaml
services:
  myapp:
    image: myapp-image:latest
    deploy:
      mode: replicated # global another option
      replicas: 3
    volumes:
      - named-volume:/app/data
    environment:
      - ENV_VAR_1=value1
      - ENV_VAR_2=value2
    cap_add:
      - CAPABILITY_NAME
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_syncookies=0
    command: ["custom_command", "arg1", "arg2"]
```

---

There will be some special variable which can be included for generate service name
- **STACK_NAME** : _Global Variabke_ We can define a service name like {{STACK_NAME}}_myapp
- **#** : Random number. To generate random number. i.e. for random 4 digits {{####}
- **$** : Random character. To generate random character. i.e. for random 4 character {{$$$$}}
- **RANDOM_** prefix: any specific variable name starting with this prefix will be replaced by a random alphanumeric string. {{RANDOM_REDIS_PASSWORD}}

---

For internal use and one-click app installer docs, alongside `services` section in stack yaml, there will be `docs` section.

```yaml
docs:
  logo_url: img
  name: Redis
  description: "in-memory data structure store, used as a database, cache, and message broker"
  readme_description:  "#### dummy"
  iframe_video_embed: ""
  variables:
    VARIABLE_NAME:
      title: "Redis Password"
      description: "Password to protect your redis db from unauthorized access"
      default: adminpass
      type: text # text, int, float, options, volume, application
      options:
        - title: v4
          value: 4
        - title: v3
          value: 3
```

**Comment by prologic** [comment]
Stack

**Comment by tanmoysrt** [comment]
Swiftwave will provide support for a subset of Stack features. (It will power one click app store [in future])

```yaml
services:
  myapp:
    image: myapp-image:latest
    deploy:
      mode: replicated # global another option
      replicas: 3
    volumes:
      - named-volume:/app/data
    environment:
      - ENV_VAR_1=value1
      - ENV_VAR_2=value2
    cap_add:
      - CAPABILITY_NAME
    command: ["custom_command", "arg1", "arg2"]
```

---

There will be some special variable which can be included for generate service name
- **STACK_NAME** : _Global Variabke_ We can define a service name like {{STACK_NAME}}_myapp
- **#** : Random number. To generate random number. i.e. for random 4 digits {{####}
- **$** : Random character. To generate random character. i.e. for random 4 character {{$$$$}}
- **RANDOM_** prefix: any specific variable name starting with this prefix will be replaced by a random alphanumeric string. {{RANDOM_REDIS_PASSWORD}}
